[mypy]
python_version = 3.12
mypy_path = src
files = src
warn_unused_ignores = True

[mypy-transformers]
ignore_missing_imports = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-vision_forge_api.config]
ignore_missing_imports = True

[mypy-vision_forge_api.config.*]
ignore_missing_imports = True
